#!/usr/bin/env bash
# Block edits to tool-owned / generated files in the dotfiles repo, so they're
# changed via their owning tool instead of by hand.
#
# PreToolUse hook on Edit|Write|MultiEdit. Reads the tool-call JSON on stdin and
# exits 2 (with the reason on stderr) to block when the target path is managed.
set -uo pipefail

input=$(cat)
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -n "$file_path" ] || exit 0

base=${file_path##*/}

block() {
  printf 'Refusing to edit %s: %s\n' "$file_path" "$1" >&2
  exit 2
}

case "$file_path" in
*/LICENSES/*) block "REUSE-managed; add license texts with the reuse tool, not by hand." ;;
*/iterm2/*.plist) block "binary iTerm2 plist; export it from iTerm2 rather than hand-editing." ;;
esac

case "$base" in
uv.lock) block "generated lockfile; run 'uv lock' (or 'uv add'/'uv remove') instead." ;;
CHANGELOG.md) block "generated by release-please; don't hand-edit." ;;
esac

exit 0
