# SPDX-FileCopyrightText: © 2026 Tyler Nivin
# SPDX-License-Identifier: MIT

# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v1.0.1
_src_path: gh:nivintw/copier-everything
author_email: tyler@nivin.tech
author_name: Tyler Nivin
contains_python: true
include_devcontainer: false
include_docker: false
include_helm: false
include_sql: false
include_terraform: false
license: MIT
markdown_has_frontmatter: true
project_description: Tyler Nivin's dotfiles and config repo
project_name: dotfiles
project_slug: dotfiles
python_source: false
python_version: '3.14'
repo_owner: nivintw
test_frameworks:
- pytest
- bats
year: 2026
