# SPDX-FileCopyrightText: © 2026 Tyler Nivin
# SPDX-License-Identifier: MIT

"""Phase 3: symlink the dotfiles into ``$HOME`` with GNU stow.

Stow refuses to overwrite an existing *real* file, so first clear the known tool-generated
files (:data:`MANAGED_FILES`) — removing one byte-identical to the repo copy, backing up a
divergent one to a numbered ``*.pre-stow.bak`` (never destroyed). Then migrate the git template
hooks to the notify-on-clone design (drop only prek-generated shims) and adopt a pre-existing
``~/.gitconfig`` (:func:`~dotfiles_install.gitconfig_migrate.gitconfig_migrate`). A dry-run
``stow --no-folding -n`` preflight surfaces every conflict up front; a conflict (or a failed
gitconfig adoption) is **fatal** (exit 1) so the user resolves it rather than losing config.

:data:`MANAGED_FILES` is the Python source of truth the test suite checks (it used to scrape
the bash ``managed_files=(...)`` array); a consistency test keeps the two in step until the
``install.sh`` cutover (#72).

Ported from ``install.sh`` phase 3 (the "Symlink dotfiles into $HOME" block).
"""

from __future__ import annotations

import filecmp
from pathlib import Path
from typing import TYPE_CHECKING

from dotfiles_install import commands
from dotfiles_install.gitconfig_migrate import gitconfig_migrate, next_backup_path
from dotfiles_install.layout import DOTFILES

if TYPE_CHECKING:
    from dotfiles_install.context import InstallContext

# $HOME-relative paths that tools may generate as real files on first run, which stow would
# then refuse to overwrite. The source of truth for tests/test_consistency.py — kept in step
# with the bash `managed_files=(...)` array by a parity test until the #72 cutover.
MANAGED_FILES: tuple[str, ...] = (
    "Library/Application Support/Code/User/settings.json",  # VS Code / Settings Sync
    ".config/atuin/config.toml",  # atuin writes a default on first run
    ".config/topgrade.toml",  # topgrade --edit-config seeds a default
)

# The prek shim marker: prek writes this into every hook it generates, so it identifies a
# regenerable shim (safe to remove) versus a hand-written hook (left to surface as a conflict).
_PREK_SHIM_MARKER = "File generated by prek"


def stow_dotfiles(ctx: InstallContext) -> None:
    """Clear managed files, migrate the git template + gitconfig, then stow ``home/``.

    The four steps run in install.sh's order; the last two (gitconfig adoption, stow preflight)
    can exit 1.
    """
    _clear_managed_files(ctx)
    _migrate_git_template_hooks(ctx)
    _migrate_gitconfig(ctx)
    _stow_preflight_and_apply(ctx)
    ctx.ui.ok("dotfiles symlinked (stow, 0 conflicts)")


def _clear_managed_files(ctx: InstallContext) -> None:
    """Remove/back up real files that would block stow (only real files, never symlinks)."""
    home = Path.home()
    for rel in MANAGED_FILES:
        target = home / rel
        # Act only on a real file: skip symlinks (already stow-managed) and missing paths.
        if not target.is_file() or target.is_symlink():
            continue
        repo_src = DOTFILES / "home" / rel
        if not repo_src.exists():
            # No repo copy means stow won't link it — leave the user's file untouched.
            ctx.ui.warn(f"no repo copy for {target} (skipping; not a stow-managed path)")
            continue
        if filecmp.cmp(target, repo_src, shallow=False):
            ctx.ui.active(f"removing existing real file so stow can symlink it: {target}")
            # Identical to the repo copy — nothing to preserve; unlink ignores write-protection
            # (like the bash `rm -f`), so a read-only managed file can't stall the run.
            target.unlink()
        else:
            backup = next_backup_path(target)
            ctx.ui.warn(f"backing up modified {target} -> {backup} (differs from the repo version)")
            target.rename(backup)


def _migrate_git_template_hooks(ctx: InstallContext) -> None:
    """Remove prek-generated template-hook shims so the tracked notify-on-clone hook can land.

    Only prek's own generated shims are removed (matched by its marker) — a hand-written hook at
    this path is left to surface as a loud stow conflict, never clobbered.
    """
    tmpl_hooks = Path.home() / ".config" / "git" / "template" / "hooks"
    if not tmpl_hooks.is_dir():
        return
    removed: list[str] = []
    # Skip dotfiles to match the bash `"$tmpl_hooks"/*` glob (which ignores hidden entries).
    for hook in sorted(p for p in tmpl_hooks.iterdir() if not p.name.startswith(".")):
        if hook.is_symlink():
            continue
        if _PREK_SHIM_MARKER in commands.read_text_or_empty(hook):
            hook.unlink()
            removed.append(hook.name)
    if removed:
        shims = "".join(f" {name}" for name in removed)
        ctx.ui.active(f"migrated git template to notify-on-clone (removed prek shims:{shims})")


def _migrate_gitconfig(ctx: InstallContext) -> None:
    """Adopt a pre-existing ``~/.gitconfig`` into the overlay; a failed adoption is fatal."""
    home = Path.home()
    try:
        action = gitconfig_migrate(
            home / ".gitconfig",
            home / ".gitconfig_local",
            DOTFILES / "home" / ".gitconfig",
        )
    except OSError as exc:
        # gitconfig_migrate raises a bare OSError; surface it so the message isn't an empty
        # "see the error above" pointing at nothing.
        ctx.ui.err(f"couldn't safely adopt your existing ~/.gitconfig: {exc}")
        ctx.ui.detail(
            "Your config was left in place or backed up to ~/.gitconfig.pre-stow.bak — "
            "resolve it, then re-run install.sh.",
        )
        raise SystemExit(1) from exc
    if not action:
        return
    if action.startswith("backed up"):
        ctx.ui.warn(action)
    else:
        ctx.ui.active(action)


def _stow_preflight_and_apply(ctx: InstallContext) -> None:
    """Dry-run stow to surface every conflict (fatal if any), then apply it for real."""
    opts = [f"--dir={DOTFILES}", f"--target={Path.home()}", "home"]
    ctx.ui.active("checking for conflicts (dry run)")
    preflight = commands.run(["stow", "--no-folding", "-n", "-v", *opts], capture=True)
    if preflight.returncode:
        # stow -v writes its plan to stderr; the bash original merges 2>&1, so combine both.
        plan = (preflight.stdout or "") + (preflight.stderr or "")
        ctx.ui.err(
            "these files already exist in $HOME and would be replaced by this repo's versions, "
            "so aborting.",
        )
        ctx.ui.detail(
            "Back them up and/or merge their contents into the repo, then re-run install.sh:",
        )
        conflicts = [line for line in plan.splitlines() if "cannot stow" in line]
        for line in conflicts or plan.splitlines():
            ctx.ui.detail(line)
        raise SystemExit(1)
    if not commands.run_ok(["stow", "--no-folding", *opts]):
        ctx.ui.err("stow failed to symlink the dotfiles despite a clean preflight.")
        raise SystemExit(1)
